# GitHub Workflow to execute test cases via Principal Mapper

name: "PMapper Checks"

# Run when PR against main comes through with infracode/testcode changes
on:
  pull_request:
    branches:
      - main
    paths:
      - "infracode/**"
      - "testcode/**"
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:


jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Graphviz
        run: "sudo apt-get install -y graphviz jq"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Init Terraform
        run: | 
          cd $GITHUB_WORKSPACE/infracode
          terraform init
      - name: Validate Config
        run: |
          cd $GITHUB_WORKSPACE/infracode
          terraform validate -no-color
      - name: Setup LocalStack
        run: |
          echo "Install LocalStack, AWS CLI, PMapper, Scout Suite via pip"
          pip install localstack principalmapper
          echo "Pull localstack/localstack from Docker"
          docker pull localstack/localstack
          echo "Start LocalStack"
          localstack start -d
          echo "Wait for LocalStack"
          localstack wait -t 30
          echo "LocalStack running"
      - name: Deploy Infra Code
        run: |
          cd $GITHUB_WORKSPACE/infracode
          terraform apply -auto-approve -var "acctid=000000000000"
      - name: Make Artifacts Directory
        run: |
          mkdir -p /tmp/artifacts
      - name: Create PMapper Graph
        env:
          PMAPPER_STORAGE: "/tmp/artifacts"
          AWS_ACCESS_KEY_ID: AKIAFAKEFAKEFAKE
          AWS_SECRET_ACCESS_KEY: alsofakejustmakesthingswork
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
        run: |
          pmapper graph create --localstack-endpoint http://localhost:4566 --include-regions us-east-1 --exclude-services autoscaling 
          pmapper --account 000000000000 visualize
          mv 000000000000.svg /tmp/artifacts/visualization.svg
          pmapper --account 000000000000 analysis --output-type text > /tmp/artifacts/analysis.md
      - name: Generate PMapper Graph Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Account Graph
          path: |
            /tmp/artifacts/*.svg
            /tmp/artifacts/*.md
      - name: Execute PMapper Test Cases
        continue-on-error: true
        env:
          PMAPPER_STORAGE: "/tmp/artifacts"
        run: |
          cd $GITHUB_WORKSPACE/testcode
          echo $((python -m unittest -v test_permissions.py) 2> results.txt)
          cat results.txt
          echo -e 'PMapper Test Results:\n\n```' > header.txt
          echo -e '\n```' > footer.txt
          cat header.txt results.txt footer.txt > full_output.txt
          jq -Rs '{ body: . }' full_output.txt > json_output.txt
        id: pmappertests
      - name: Update PR
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          curl -X POST \
          --user ${{ github.actor }}:$GITHUB_TOKEN \
          -H 'Accept: application/vnd.github.v3+json' \
          --data "@$GITHUB_WORKSPACE/testcode/json_output.txt" \
          "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/issues/${{ github.event.pull_request.number }}/comments"

      - name: Process Test Results
        run: |
          cd $GITHUB_WORKSPACE/testcode
          python -c 'import sys; sys.exit(1) if "FAILED" in open("results.txt").read() else sys.exit(0)'
